### ISSUE TITLE
List volumes fails on CSI v0.3 

### ISSUE THREAD

**Issue by Akrog** [embercsi/ember-csi#97]
Listing volumes when running with CSI v0.3 will raise an exception:

```
2019-03-05 13:02:50 ERROR root [req-140029023167384] Exception calling application: 'All' object has no attribute 'TOPOLOGIES': AttributeError: 'All' object has no attribute 'TOPOLOGIES'
2019-03-05 13:02:50.626 27782 ERROR root Traceback (most recent call last):
2019-03-05 13:02:50.626 27782 ERROR root   File "/home/geguileo/code/reuse-cinder-drivers/ember/.tox/py27/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
2019-03-05 13:02:50.626 27782 ERROR root     return behavior(argument, context), True
2019-03-05 13:02:50.626 27782 ERROR root   File "/home/geguileo/code/reuse-cinder-drivers/ember/ember_csi/common.py", line 124, in dolog
2019-03-05 13:02:50.626 27782 ERROR root     result = f(self, request, context)
2019-03-05 13:02:50.626 27782 ERROR root   File "/home/geguileo/code/reuse-cinder-drivers/ember/ember_csi/common.py", line 219, in checker
2019-03-05 13:02:50.626 27782 ERROR root     return f(self, request, context)
2019-03-05 13:02:50.626 27782 ERROR root   File "/home/geguileo/code/reuse-cinder-drivers/ember/ember_csi/common.py", line 76, in wrapper
2019-03-05 13:02:50.626 27782 ERROR root     return func(self, request, context)
2019-03-05 13:02:50.626 27782 ERROR root   File "/home/geguileo/code/reuse-cinder-drivers/ember/ember_csi/base.py", line 352, in CreateVolume
2019-03-05 13:02:50.626 27782 ERROR root     volume = self._convert_volume_type(vol)
2019-03-05 13:02:50.626 27782 ERROR root   File "/home/geguileo/code/reuse-cinder-drivers/ember/ember_csi/v0_3_0/csi.py", line 83, in _convert_volume_type
2019-03-05 13:02:50.626 27782 ERROR root     if self.TOPOLOGIES:
2019-03-05 13:02:50.626 27782 ERROR root AttributeError: 'All' object has no attribute 'TOPOLOGIES'
```

**Comment by kirankt** [comment]
Ran into this issue while testing on OCP 3.11. For the moment, reverted back to CSI_SPEC v0.2.0 until this is fixed.
